
spring:
  application:
    name: appbuilder

  datasource:
    url: jdbc:postgresql://localhost:5000/app-builder
    username: user
    password: super-secret-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
